/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { CrawlResultListRelationFilter } from "../../crawlResult/base/CrawlResultListRelationFilter";
import { CrawlOptionListRelationFilter } from "../../crawlOption/base/CrawlOptionListRelationFilter";

@InputType()
class WebsiteWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  url?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  crawlDepth?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: () => CrawlResultListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CrawlResultListRelationFilter)
  @IsOptional()
  @Field(() => CrawlResultListRelationFilter, {
    nullable: true,
  })
  crawlResults?: CrawlResultListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => CrawlOptionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CrawlOptionListRelationFilter)
  @IsOptional()
  @Field(() => CrawlOptionListRelationFilter, {
    nullable: true,
  })
  crawlOptions?: CrawlOptionListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  readme?: StringNullableFilter;
}

export { WebsiteWhereInput as WebsiteWhereInput };
