/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { WebsiteService } from "../website.service";
import { WebsiteCreateInput } from "./WebsiteCreateInput";
import { Website } from "./Website";
import { WebsiteFindManyArgs } from "./WebsiteFindManyArgs";
import { WebsiteWhereUniqueInput } from "./WebsiteWhereUniqueInput";
import { WebsiteUpdateInput } from "./WebsiteUpdateInput";
import { CrawlResultFindManyArgs } from "../../crawlResult/base/CrawlResultFindManyArgs";
import { CrawlResult } from "../../crawlResult/base/CrawlResult";
import { CrawlResultWhereUniqueInput } from "../../crawlResult/base/CrawlResultWhereUniqueInput";
import { CrawlOptionFindManyArgs } from "../../crawlOption/base/CrawlOptionFindManyArgs";
import { CrawlOption } from "../../crawlOption/base/CrawlOption";
import { CrawlOptionWhereUniqueInput } from "../../crawlOption/base/CrawlOptionWhereUniqueInput";

export class WebsiteControllerBase {
  constructor(protected readonly service: WebsiteService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Website })
  async createWebsite(
    @common.Body() data: WebsiteCreateInput
  ): Promise<Website> {
    return await this.service.createWebsite({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        url: true,
        crawlDepth: true,
        readme: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Website] })
  @ApiNestedQuery(WebsiteFindManyArgs)
  async websites(@common.Req() request: Request): Promise<Website[]> {
    const args = plainToClass(WebsiteFindManyArgs, request.query);
    return this.service.websites({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        url: true,
        crawlDepth: true,
        readme: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Website })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async website(
    @common.Param() params: WebsiteWhereUniqueInput
  ): Promise<Website | null> {
    const result = await this.service.website({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        url: true,
        crawlDepth: true,
        readme: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Website })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateWebsite(
    @common.Param() params: WebsiteWhereUniqueInput,
    @common.Body() data: WebsiteUpdateInput
  ): Promise<Website | null> {
    try {
      return await this.service.updateWebsite({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          url: true,
          crawlDepth: true,
          readme: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Website })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteWebsite(
    @common.Param() params: WebsiteWhereUniqueInput
  ): Promise<Website | null> {
    try {
      return await this.service.deleteWebsite({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          url: true,
          crawlDepth: true,
          readme: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/crawlResults")
  @ApiNestedQuery(CrawlResultFindManyArgs)
  async findCrawlResults(
    @common.Req() request: Request,
    @common.Param() params: WebsiteWhereUniqueInput
  ): Promise<CrawlResult[]> {
    const query = plainToClass(CrawlResultFindManyArgs, request.query);
    const results = await this.service.findCrawlResults(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        pageUrl: true,
        result: true,

        website: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/crawlResults")
  async connectCrawlResults(
    @common.Param() params: WebsiteWhereUniqueInput,
    @common.Body() body: CrawlResultWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      crawlResults: {
        connect: body,
      },
    };
    await this.service.updateWebsite({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/crawlResults")
  async updateCrawlResults(
    @common.Param() params: WebsiteWhereUniqueInput,
    @common.Body() body: CrawlResultWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      crawlResults: {
        set: body,
      },
    };
    await this.service.updateWebsite({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/crawlResults")
  async disconnectCrawlResults(
    @common.Param() params: WebsiteWhereUniqueInput,
    @common.Body() body: CrawlResultWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      crawlResults: {
        disconnect: body,
      },
    };
    await this.service.updateWebsite({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/crawlOptions")
  @ApiNestedQuery(CrawlOptionFindManyArgs)
  async findCrawlOptions(
    @common.Req() request: Request,
    @common.Param() params: WebsiteWhereUniqueInput
  ): Promise<CrawlOption[]> {
    const query = plainToClass(CrawlOptionFindManyArgs, request.query);
    const results = await this.service.findCrawlOptions(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        optionValue: true,
        optionName: true,

        website: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/crawlOptions")
  async connectCrawlOptions(
    @common.Param() params: WebsiteWhereUniqueInput,
    @common.Body() body: CrawlOptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      crawlOptions: {
        connect: body,
      },
    };
    await this.service.updateWebsite({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/crawlOptions")
  async updateCrawlOptions(
    @common.Param() params: WebsiteWhereUniqueInput,
    @common.Body() body: CrawlOptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      crawlOptions: {
        set: body,
      },
    };
    await this.service.updateWebsite({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/crawlOptions")
  async disconnectCrawlOptions(
    @common.Param() params: WebsiteWhereUniqueInput,
    @common.Body() body: CrawlOptionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      crawlOptions: {
        disconnect: body,
      },
    };
    await this.service.updateWebsite({
      where: params,
      data,
      select: { id: true },
    });
  }
}
